name: CI

on:
  create:
    branches:
      - release/**
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    env:
      BUILD_CONFIG: 'Release'
      SOLUTION: 'DateTimeProviders.sln'
    
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Get Build Version
        run: |
          Import-Module .\build\GetBuildVersion.psm1
          Write-Host $Env:GITHUB_REF
          $version = GetBuildVersion -VersionString $Env:GITHUB_REF
          echo "BUILD_VERSION=$version" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf-8 -Append
        shell: pwsh

      - name: Setup .NET
        uses: actions/setup-dotnet@v3.4.2
        with:
          dotnet-version: 8.0.x

      - name: Setup NuGet
        uses: nuget/setup-nuget@v2.0.0
      
      - name: Restore dependencies
        run: dotnet restore $SOLUTION

      - name: Build
        run: dotnet build $SOLUTION --configuration $BUILD_CONFIG -p:Version=$BUILD_VERSION --no-restore

      - name: Publish
        if: startsWith(github.ref, 'refs/heads/release')
        run: dotnet nuget push **\*.nupkg --source "GPR" --skip-duplicate --api-key ${{secrets.NUGET_API_KEY}}
